

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - backend
